# Generated by Django 4.2.5 on 2023-09-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='detected_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Fire_grow', models.IntegerField()),
                ('smoke_grow', models.IntegerField()),
                ('CAM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.cam')),
            ],
        ),
    ]
